---
baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
menu:
  main:
  - name: test2
    url: "/test2"
    weight: 1
  - identifier: index
    title: about
    url: "/"
    name: test
    weight: 1
