---
baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
menu:
  main:
  - identifier: test
    title: Test
    url: "/test/"
    weight: 2
  - identifier: index
    title: About
    url: "/"
    weight: 1
params:
  image_url: https://example.com
